config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :users
  resources :sessions
  namespace :admin do
    resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    end
  end
  root 'sessions#new'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true,length: { maximum: 400 }
  validates :deadline, presence: true
  validates :status, presence: true
  validates :priority, presence: true

  enum status: { not_yet: 0, in_progress: 1, completed: 2 }
  enum priority: { high: 1, middle: 2, low: 3 }
  
  belongs_to :user
  #binding.pry
  
  scope :title_search, -> (title) {
    where("title LIKE ?","%#{ title }%")
  }

  scope :status_search, -> (status) {
    where(status: status)
  }

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  has_many :tasks, dependent: :destroy

  before_destroy :ensure_admin_deatroy
  before_update :ensure_admin_update

  def ensure_admin_deatroy
    throw(:abort) if User.where(admin: true).count <= 1 && self.admin == true
  end

  def ensure_admin_update
    if User.where(admin: true).count == 1 && self.admin == false
      errors.add(:admin,"は、最低でも１人は必要です。")
      throw(:abort)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]
  before_action :require_admin

  def index
    @users = User.all.includes(:tasks) #N+1問題
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path,notice: "ユーザーを新しく登録しました。"
    else
      render :new
    end
  end

  def show
    @tasks = @user.tasks
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザー情報を変更しました。"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました。"
    else
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    if current_user.nil? || !current_user.admin?
      redirect_to tasks_path, notice: "管理者以外はアクセスできません。"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      flash[:notice] = "ログインに成功しました。"
      # 管理者画面とユーザー画面の分岐
      if user.admin?
        redirect_to admin_users_path(user.id)  #管理者画面
      else
        redirect_to user_path(user.id)    #ユーザー画面
      end
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました。'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :login_require

  # PER = 5
  # GET /tasks or /tasks.json
  def index

    @tasks = current_user.tasks
    @tasks = @tasks.order(deadline: :desc) if params[:sort_expired]
    @tasks = @tasks.order(priority: :asc) if params[:sort_priority_high]

    if params[:search].present?
      @tasks = @tasks.title_search(params[:search][:title]) if params[:search][:title].present?
      @tasks = @tasks.status_search(params[:search][:status]) if params[:search][:status].present?
    end

    @tasks = @tasks.page(params[:page]).per(5)
  end

    # #if params[:search].present?
    #   #binding.pry
    #   #if params[:search][:title].present? && params[:search][:status].present?
    #     #両方title and statusが成り立つ検索結果を返す
    #     #@tasks = @tasks.title_search(params[:search][:title])
    #     @tasks = @tasks.status_search(params[:search][:status])
        
    #     #渡されたパラメータがtask titleのみだったとき
    #   elsif params[:search][:title].present?
    #     @tasks = @tasks.title_search(params[:search][:title])
      
    #    #渡されたパラメータがステータスのみだったとき
    #   elsif params[:search][:status].present?
    #     @tasks = @tasks.status_search(params[:search][:status])
       
    #     #推しただけ
    #   #elsif params[:title].present=nil && params[:status].present=nil
    #    # @tasks = @tasks.order(created_at: :desc).page(params[:page]).per(PER)
    #   end
    # end
    #end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    #@task = Task.new(task_params)
    @task = current_user.tasks.new(task_params)
    
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "タスクが登録されました。" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "タスクが更新されました。" }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "タスクが削除されました。" }
      format.json { head :no_content }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end
  
  def login_require
    redirect_to new_session_path unless current_user
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :content, :status, :priority, :deadline)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only:[:show,:edit ,:update]

  def new
    @user = User.new
  end

  def edit
    if logged_in?
      flash[:danger] = '権限がありません。'
      redirect_to tasks_path
    end
  end

  def show
    @tasks = @user.tasks
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "アカウント作成後、ログインしました。"
      @tasks = current_user.tasks
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "ユーザー情報を変更しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
  
  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: [:admin, @user], local: true) do |form| %>
    <div class="user_list">
      <p><%= form.label :name %></p>
      <p><%= form.text_field :name %></p>
    </div>

    <div class="user_list">
      <p><%= form.label :email %><p>
      <p><%= form.email_field :email %></p>
    </div>

    <div class="user_list">
      <p><%= form.label :管理者権限 %></p>
      <p><%= form.check_box :admin %></p>
    </div>

    <div class="user_list">
      <p><%= form.label :password %></p>
      <p><%= form.password_field :password %></p>
    </div>

    <div class="user_list">
      <p><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation %></p>
    </div> 
    
      <%= form.submit %>
  
<% end %>

app/views/admin/users/edit.html.erb
<h4><%= @user.name %>のページ編集</h4>
<br>
<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<h3>管理画面：ユーザーの一覧確認ページ</h3><br>


<table class="table">
<br>
  <thead>
    <tr class="table-info">
      <th><%= t('user.id') %></th>
      <th><%= t('user.name') %></th>
      <th><%= t('user.admin') %></th>
      <th><%= t('user.task_count') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <% if user.admin? %>
          <td>管理者</td>
        <% else %>
          <td>一般</td>
        <% end %>
        <td><%= user.tasks.count %></td>
        <td><%= link_to '情報', admin_user_path(user), id: "users_admin_show" %></td>
        <td><%= link_to '編集', edit_admin_user_path(user), id: "users_admin_index_edit" %></td>
        <td class="user_row"><%= link_to '削除', admin_user_path(user.id), id: "users_admin_index_delete", method: :delete, data:{ confirm: "本当に削除してよろしいですか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<br>


<%= render 'form', user: @user %>

app/views/admin/users/show.html.erb
<h4><%= @user.name %>のページ</h4>
<table class="col-md-12">
  <thead>
    <tr>
      <th class="col-md-2">タスク</th>
      <th class="col-md-3" >詳細</th>
      <th class="col-md-2">期限</th>
      <th class="col-md-1">ステータス</th>
      <th class="col-md-1">優先度</th>
      <th class="col-md-1">閲覧</th>
      <th class="col-md-1">編集</th>
      <th class="col-md-1">削除</th>
    </tr>
  </thead>
  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td id = 'task_list' ><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status_i18n %></td>
        <td><%= task.priority_i18n %></td>
        <td><button type="button" class="btn btn-warning btn-sm"><%= link_to '詳細', task %></button></td>
        <td><button type="button" class="btn btn-warning btn-sm"><%= link_to '編集', edit_task_path(task) %></button></td>
        <td><button type="button" class="btn btn-danger btn-sm"><%= link_to '削除', task, method: :delete, data: { confirm: '削除しますか？' } %></button></td>
       </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Task List</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      </div>

      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <p class="navbar-brand">Task List</p>
          <% if logged_in? %>
            <li><%= link_to 'タスク登録', new_task_path %></li>
            <li><%= link_to 'タスク一覧', tasks_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>


    <div class="contents">  
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    
      <% if logged_in? %>
        <button type="button" class="btn btn-info" id = user_edit><%= link_to "ユーザー編集", edit_user_path(current_user.id) %></button>
        <button type="button" class="btn btn-danger" id = logout><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></button>
        <h4><%= current_user.name %>としてログイン中</h4>
        <% if current_user.admin? %>
          <button type="button" class="btn btn-warning"><%= link_to "管理者用ユーザ一覧", admin_users_path %></button>
          <button type="button" class="btn btn-warning"><%= link_to "管理者用ユーザ一作成", new_admin_user_path , id: "users_admin_new_link" %></button>
        <% end %>
      <% end %> 
    
      <%= yield %>

    </div>

  </body>

</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_list">
    <p><%= form.label :title %></p>
    <p><%= form.text_field :title %></p>
  </div>

  <div class="task_list">
    <p><%= form.label :content %></p>
    <p><%= form.text_area :content %></p>
  </div>

  <div class="task_list">
    <p><%= form.label :priority %></p>
    <p><%= form.select :priority, Task.priorities.keys.map {|k| [I18n.t("enums.tasks.priority.#{k}"), k]}, include_blank: "選択して下さい" %></p>
  </div> 

  <div class="task_list">
    <p><%= form.label :status %></p>
    <p><%= form.select :status, Task.statuses.keys.map {|k| [I18n.t("enums.tasks.status.#{k}"), k]}, include_blank: "選択して下さい" %></p>
  </div>

  <div class="task_list">
    <p><%= form.label :deadline %></p>
    <p><%= form.date_field(
          :deadline, id: "deadline", class: "form-control",
          use_month_numbers: true, # jan, febとかじゃなくて数字で月を表現
          start_year:     (Time.now.year), # 何年から表示させるか
          end_year:       (Time.now.year), # 何年まで表示させるか
          default:        Date.new(1989, 1, 1), # 最初に表示されている年月日
          date_separator: '/') # 年月日を仕切る文字
        %></p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<body>
<div class = "container-fluid">
  <ul class="row">
    <%= form_with(scope: :search, local: true, url: tasks_path, method: :get) do |form| %>
      <li><%= form.label :title, 'タスク名:', class:'ml-5' %><li/>
      <li  id ="title" ><%= form.text_field :title %><li/>
      <li><%= form.label :status, 'ステータス:', class:'ml-5'%><li/>
      <li id ="status"><%= form.select  :status, [["未着手", "0"], ["着手中", "1"], ["完了", "2"]], include_blank: '選択してください' %><li/>
      <br>
      <li id= "search"><button type="button" class="btn btn-dark" ><%= form.submit '検索', class:'ml-3'  %></button><li/>
    <% end %>
  </ul>
</div>
  <P>
  <button type="button" class="btn btn-warning btn-sm"><%= link_to 'タスク作成', new_task_path %></button>
  </P>
  <p>
  <button type="button" class="btn btn-info btn-sm" id="sort_deadline"><%=  link_to "終了期限でソートする", tasks_path(sort_expired: "true") %></button>
  <button type="button" class="btn btn-info btn-sm" id="sort_priority"><%= link_to "優先度高い順でソート", tasks_path(sort_priority_high: "true") %></button>
  </p>
<table class="col-md-12">
  <thead>
    <tr>
      <th class="col-md-2">タスク</th>
      <th class="col-md-2">作成者</th>
      <th class="col-md-3" >詳細</th>
      <th class="col-md-2">期限</th>
      <th class="col-md-1">ステータス</th>
      <th class="col-md-1">優先度</th>
      <th class="col-md-1">閲覧</th>
      <th class="col-md-1">編集</th>
      <th class="col-md-1">削除</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td id = 'task_list' ><%= task.title %></td>
        <td><%= task.user.name %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status_i18n %></td>
        <td><%= task.priority_i18n %></td>
        <td id = 'task_detail'><%= link_to '詳細', task %></td>
        <td id = 'task_edit'><%= link_to '編集', edit_task_path(task) %></td>
        <td id = 'task_delete'><%= link_to '削除', task, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
     <%= paginate @tasks %>
  </tbody>
</table>
</body>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>


<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @task.title %>
</p>
<p>
  <strong>内容:</strong>
  <%= @task.content %>
</p>
<p>
  <strong>優先順位:</strong>
  <%= @task.priority_i18n %>
</p>
<p>
  <strong>ステータス:</strong>
  <%= @task.status_i18n %>
</p>
<p>
  <strong>終了期限:</strong>
  <%= @task.deadline %>
</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit ,user_path %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h4>マイプロフィール編集</h4>
<p>パスワード変更がない場合も、再入力をお願いします。</p>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |form| %>

    <div class="user_list">
      <p><%= form.label :name %></p>
      <p><%= form.text_field :name %></p>
    </div>

    <div class="user_list">
      <p><%= form.label :email %><p>
      <p><%= form.email_field :email %></p>
    </div>

    <div class="user_list">
      <p><%= form.label :password %></p>
      <p><%= form.password_field :password %></p>
    </div>

    <div class="user_list">
      <p><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation %></p>
    </div>
    
  <p><%= form.submit "更新する" %></p>
<% end %>

<button type="button" class="btn btn-info btn-sm"><%= link_to "マイページに戻る", user_path(current_user.id) %></button>

app/views/users/new.html.erb
<h1>新規登録</h1>
<br>
<br>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>  
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>
  <p><%= f.label :email %></p>
  <p><%= f.email_field :email %></p>
  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "アカウント作成" %></p>
  
<% end %>

アカウントをお持ちの方は<%= link_to "こちらのログインページへ", new_session_path %>

app/views/users/show.html.erb
<table class="col-md-12">
  <thead>
    <tr>
      <th class="col-md-2">タスク</th>
      <th class="col-md-2">ユーザー</th>
      <th class="col-md-3" >詳細</th>
      <th class="col-md-2">期限</th>
      <th class="col-md-1">ステータス</th>
      <th class="col-md-1">優先度</th>
    </tr>
  </thead>
  <tbody>
    <% if @tasks.count > 0  %>
      <% @tasks.each do |task| %>
        <tr>
          <td id = 'task_list' ><%= task.title %></td>
          <td><%= task.user.name %></td>
          <td><%= task.content %></td>
          <td><%= task.deadline %></td>
          <td><%= task.status_i18n %></td>
          <td><%= task.priority_i18n %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>